export AWSIP=$1
source ~/confluence-test.env

echo "./aws-00-start.sh $AWSIP $MYCAS $DBIP $DBNAME $DBUSER $DBUSERPW $CONBUILD $CONID $CONLIC $KSPP $KSPW"
./aws-00-start.sh $AWSIP $MYCAS $DBIP $DBNAME $DBUSER $DBUSERPW $CONBUILD $CONID $CONLIC $KSPP $KSPW

